### ISSUE TITLE
Buttons are not clickable

### ISSUE THREAD

**Issue by aelkady** [mcataford/spelldown#7]
The buttons for the letters should be clickable, or at least there should be copy that communicates to the user that typing is the way to input answers - clicking the buttons was my first intuitive reaction.

**Defintion of Done**
- Make the buttons clickable
- Communicate properly to the user all the ways of inputting answers

**Comment by mcataford** [comment]
@aelkady I just pushed up #11 and #10 which should address this, let me know what you think!

**Comment by aelkady** [comment]
@mcataford it looks great! Saying that the words have to be at least 4 letters long made it make sense why some of my answers were invalid. I will say one thing, it looks like you can press enter on the keyboard to submit your answer but there is no "submit" button you can click in the interface. Would be nice to have to avoid the context switch between keyboard and mouse/trackpad but I'll leave you to file that as a separate issue.

**Comment by mcataford** [comment]
I'll add that in in the morning!

**Comment by mcataford** [comment]
Added some buttons in #12 

cc @aelkady

**Comment by aelkady** [comment]
Looks great!
